### ISSUE TITLE
Add support for UTM tracking

### ISSUE THREAD

**Issue by netwrkx** [YorCreative/Laravel-UrlShortener#11]
Any plans to add support for UTM tracking...

Great package.

**Comment by yordadev** [comment]
> Any plans to add support for UTM tracking...
> 
> Great package.

This would make a great addition.

My initial thought is to add another table with a relationship to the [ShortUrlClick](https://github.com/YorCreative/Laravel-UrlShortener/blob/main/src/Models/ShortUrlClick.php) table that will store the UTM_ parameters if present on click. 

The UTM_ information would show up with the Click information and be filterable.

Will add support for the following UTM Parameters:

- utm_source
- utm_medium
- utm_campaign
- utm_content
- utm_term


Since this will require a database migration, it will be a major release.

**Comment by yordadev** [comment]
> Any plans to add support for UTM tracking...
> 
> Great package.


hey @netwrkx , this feature has now been released.  [Upgrade Guide](https://github.com/YorCreative/Laravel-UrlShortener/wiki/Upgrading-to-2.x-from-1.x)
Thank you for the request, this has been a great addition to the package!
